# Generated by Django 5.1.7 on 2025-04-16 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the exercise', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of how to perform the exercise', null=True)),
                ('muscle_group', models.CharField(blank=True, help_text='Primary muscle group targeted', max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the weight was recorded')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this weight measurement', null=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the workout')),
                ('name', models.CharField(blank=True, help_text='Optional name for this workout session', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this workout session', null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=1, help_text='Number of sets performed')),
                ('reps', models.PositiveIntegerField(default=1, help_text='Number of repetitions per set')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight used (if applicable)', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this exercise performance', null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='count_calories_app.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='count_calories_app.workoutsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
