# Generated by Django 5.1.7 on 2025-04-16 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0002_exercise_weight_workoutsession_workoutexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the run')),
                ('distance', models.DecimalField(decimal_places=2, help_text='Distance in kilometers', max_digits=5)),
                ('duration', models.DurationField(help_text='Duration of the run (HH:MM:SS)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this run', null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
