# Generated by Django 5.1.7 on 2025-04-16 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0003_runningsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the workout table', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the table was created')),
                ('table_data', models.JSONField(help_text='JSON representation of the table data')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
