# Generated by Django 5.1.7 on 2025-04-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0004_workouttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calories per serving', max_digits=5),
        ),
    ]
