# Generated by Django 5.1.7 on 2025-04-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0005_alter_fooditem_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='hide_from_quick_list',
            field=models.BooleanField(default=False, help_text='Hide this item from the quick add list'),
        ),
    ]
