# Generated by Django 5.1.7 on 2025-04-20 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0007_alter_fooditem_calories'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the measurements were recorded')),
                ('neck', models.DecimalField(blank=True, decimal_places=2, help_text='Neck circumference in cm', max_digits=5, null=True)),
                ('chest', models.DecimalField(blank=True, decimal_places=2, help_text='Chest circumference in cm', max_digits=5, null=True)),
                ('belly', models.DecimalField(blank=True, decimal_places=2, help_text='Belly/waist circumference in cm', max_digits=5, null=True)),
                ('biceps', models.DecimalField(blank=True, decimal_places=2, help_text='Biceps circumference in cm', max_digits=5, null=True)),
                ('triceps', models.DecimalField(blank=True, decimal_places=2, help_text='Triceps circumference in cm', max_digits=5, null=True)),
                ('forearm', models.DecimalField(blank=True, decimal_places=2, help_text='Forearm circumference in cm', max_digits=5, null=True)),
                ('thigh', models.DecimalField(blank=True, decimal_places=2, help_text='Thigh circumference in cm', max_digits=5, null=True)),
                ('lower_leg', models.DecimalField(blank=True, decimal_places=2, help_text='Lower leg/calf circumference in cm', max_digits=5, null=True)),
                ('butt', models.DecimalField(blank=True, decimal_places=2, help_text='Butt/glutes circumference in cm', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about these measurements', null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
