# Generated by Django 5.1.7 on 2025-04-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0008_bodymeasurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='biceps',
        ),
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='forearm',
        ),
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='lower_leg',
        ),
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='thigh',
        ),
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='triceps',
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='left_biceps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Left biceps circumference in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='left_forearm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Left forearm circumference in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='left_lower_leg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Left lower leg/calf circumference in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='left_thigh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Left thigh circumference in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='left_triceps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Left triceps circumference in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='right_biceps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Right biceps circumference in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='right_forearm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Right forearm circumference in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='right_lower_leg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Right lower leg/calf circumference in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='right_thigh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Right thigh circumference in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='bodymeasurement',
            name='right_triceps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Right triceps circumference in cm', max_digits=5, null=True),
        ),
    ]
