# Generated by Django 5.2.4 on 2025-08-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0009_remove_bodymeasurement_biceps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True),
        ),
    ]
