# Generated by Django 5.2.4 on 2025-08-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0010_weight_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the profile was last updated')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profile',
            },
        ),
        migrations.RemoveField(
            model_name='weight',
            name='height',
        ),
    ]
