# Generated by Django 5.2.4 on 2026-01-17 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0011_userprofile_remove_weight_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for this API key (e.g., 'Portfolio Website')", max_length=100)),
                ('key_prefix', models.CharField(help_text='First 8 characters of the key (for identification)', max_length=8)),
                ('key_hash', models.CharField(help_text='SHA-256 hash of the full API key', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this key was created')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this key was used', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this key is currently active')),
                ('allowed_endpoints', models.JSONField(blank=True, default=list, help_text='List of allowed endpoint patterns. Empty means all endpoints allowed.')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
