# Generated by Django 5.2.4 on 2026-01-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0012_apikey_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
