# Generated by Django 5.2.4 on 2026-01-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0013_remove_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text="User's name", max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, help_text="User's age in years", null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Current weight in kg', max_digits=5, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little or no exercise)'), ('light', 'Light (exercise 1-3 days/week)'), ('moderate', 'Moderate (exercise 3-5 days/week)'), ('active', 'Active (exercise 6-7 days/week)'), ('very_active', 'Very Active (hard exercise daily)')], default='moderate', help_text='Activity level for BMR calculation', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', help_text='Gender for BMR calculation', max_length=10)),
                ('daily_calorie_target', models.PositiveIntegerField(default=2000, help_text='Daily calorie goal')),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Target weight in kg', max_digits=5, null=True)),
                ('weekly_workout_goal', models.PositiveIntegerField(default=3, help_text='Number of workouts per week goal')),
                ('protein_target', models.PositiveIntegerField(default=150, help_text='Daily protein target in grams')),
                ('carbs_target', models.PositiveIntegerField(default=200, help_text='Daily carbohydrates target in grams')),
                ('fat_target', models.PositiveIntegerField(default=65, help_text='Daily fat target in grams')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'System Default')], default='dark', help_text='Color theme preference', max_length=10)),
                ('chart_color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange'), ('pink', 'Pink')], default='blue', help_text='Primary chart color', max_length=10)),
                ('default_date_range', models.PositiveIntegerField(choices=[(7, 'Last 7 days'), (14, 'Last 14 days'), (30, 'Last 30 days'), (90, 'Last 90 days')], default=30, help_text='Default date range for analytics')),
                ('meal_reminder_enabled', models.BooleanField(default=False, help_text='Enable meal logging reminders')),
                ('meal_reminder_times', models.JSONField(blank=True, default=list, help_text="Times for meal reminders (e.g., ['08:00', '12:00', '18:00'])")),
                ('workout_reminder_enabled', models.BooleanField(default=False, help_text='Enable workout reminders')),
                ('workout_reminder_time', models.TimeField(blank=True, help_text='Time for workout reminder', null=True)),
                ('workout_reminder_days', models.JSONField(blank=True, default=list, help_text="Days for workout reminders (e.g., ['monday', 'wednesday', 'friday'])")),
                ('weight_reminder_enabled', models.BooleanField(default=False, help_text='Enable weight logging reminders')),
                ('weight_reminder_time', models.TimeField(blank=True, help_text='Time for weight reminder', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
