# Generated by Django 5.2.4 on 2026-01-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0014_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='fitness_goal',
            field=models.CharField(choices=[('maintain', 'Maintain Weight'), ('bulk', 'Bulk (Gain Muscle)'), ('cut', 'Cut (Lose Fat)')], default='maintain', help_text='Your fitness goal', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='use_auto_macros',
            field=models.BooleanField(default=True, help_text='Auto-calculate macros based on fitness goal'),
        ),
    ]
