# Generated by Django 5.2.4 on 2026-02-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_calories_app', '0015_usersettings_fitness_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='fitness_goal',
            field=models.CharField(choices=[('maintain', 'Maintain Weight'), ('bulk', 'Bulk (Gain Muscle)'), ('cut', 'Cut (Lose Fat)'), ('ripped', 'Get Ripped')], default='maintain', help_text='Your fitness goal', max_length=10),
        ),
    ]
